[package]
name = "wandpapier-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
tracing = "0.1.41"
libheif-rs = "2.4.0"
tracing-subscriber = "0.3.20"
tokio = { version = "1.47.1", features = ["full"] }

wandpapier-core = { path = "../wandpapier-core" }