[package]
name = "wandpapier-core"
version = "0.1.0"
edition = "2024"

[dependencies]
glib = "0.21.1"
rayon = "1.11.0"
anyhow = "1.0.99"
tracing = "0.1.41"
libheif-rs = { version = "2.4.0", features = ["v1_17", "embedded-libheif"] }